// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBupKiwuVB62DTE-PSl8MjxXOeW-Tvg-0o',
    appId: '1:1098627702306:android:be2e09b4e5b82d7ebd747b',
    messagingSenderId: '1098627702306',
    projectId: 'smarttable-44f51',
    storageBucket: 'smarttable-44f51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBil8LEcgAJ34Uo2w2-EE3X7Jhbm9PmNys',
    appId: '1:1098627702306:ios:bd107fa441eb7ce4bd747b',
    messagingSenderId: '1098627702306',
    projectId: 'smarttable-44f51',
    storageBucket: 'smarttable-44f51.firebasestorage.app',
    androidClientId:
        '1098627702306-g1ea7kdnu4ka0jm7cie2d2tcfmpo0s7f.apps.googleusercontent.com',
    iosBundleId: 'com.optimalsoft.smartble',
  );
}
